name: Deno

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno: ["v1.23.3"]
        os: [ubuntu-latest]

    steps:
      - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        id: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECUREs_COMMANDS=true' >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v2.4.2

      - name: Setup Deno
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366

      - name: Cache Dependecies
        run: deno cache deps.ts

      - name: Run tests
        run: deno test
