name: Deno

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: [1.23.3, 1.22.3, 1.21.3]
    name: Test with Deno ${{ matrix.deno }} 

    steps:
      - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        id: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECUREs_COMMANDS=true' >> $GITHUB_ENV
        
      - uses: actions/checkout@master

      - name: Setup Deno
        uses: denoland/setup-deno@1.1.0
        with:
          deno-version: ${{ matrix.deno }}

      - name: Cache Dependecies
        run: deno cache deps.ts

      - name: Run tests
        run: deno test
